"""
PaperTrap — Baseline 2: Zero-shot LLM Classification
- Uses Gemini (already in your stack) as the frozen classifier
- No training, no labeled data required during inference
- Structured JSON output for reliable parsing
- Full evaluation metrics + confidence calibration
"""

import os
import json
import time
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, classification_report
)
from google import genai
from google.genai import types
from dotenv import load_dotenv
load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────
GEMINI_MODEL  = "gemini-3.1-flash-lite-preview"  # frozen, no fine-tuning
MAX_WORDS     = 3000                       # project spec: fixed window
API_KEY       = os.environ.get("GEMINI_API_KEY", "")     # load from env
RETRY_LIMIT   = 3
RETRY_DELAY   = 2   # seconds between retries on API failure

# ── Prompt ────────────────────────────────────────────────────────────────────
SYSTEM_INSTRUCTION = """You are an expert academic integrity evaluator specializing in detecting AI-generated research papers.
You analyze linguistic patterns, stylometric features, and structural characteristics to distinguish human-authored papers from AI-generated ones.
You MUST respond only with valid JSON — no additional text, no markdown, no explanation outside the JSON object."""

CLASSIFICATION_PROMPT = """Analyze the following research paper excerpt and determine whether it was written by a human researcher or generated by an AI language model.

Look for these indicators of AI generation:
- Unusually uniform sentence structure and rhythm
- Generic, overly polished academic phrasing without personality
- Lack of specific domain expertise nuances or researcher voice
- High n-gram repetition rates
- Formulaic transitions and paragraph structure
- Suspiciously consistent readability level throughout
- Absence of hedging, uncertainty, or personal research insights

Look for these indicators of human authorship:
- Varied sentence length and structural diversity
- Domain-specific jargon used with precision and context
- Idiosyncratic phrasing and researcher voice
- Appropriate hedging language ("we believe", "this suggests", "surprisingly")
- References to specific limitations, failures, or unexpected findings
- Natural inconsistencies in style across sections

Paper excerpt (first 3000 words):
---
{text}
---

Respond with ONLY this JSON object (no other text):
{{
  "prediction": "human" or "ai_generated",
  "confidence": float between 0.0 and 1.0 (confidence in your prediction),
  "ai_probability": float between 0.0 and 1.0 (probability this is AI-generated),
  "top_indicators": ["list", "of", "3-5", "key", "evidence", "points"],
  "reasoning": "one sentence summary of your decision"
}}"""


# ── Core classifier ───────────────────────────────────────────────────────────

def truncate_to_words(text: str, n: int = MAX_WORDS) -> str:
    return " ".join(text.split()[:n])


def classify_paper_zero_shot(text: str, client) -> dict:
    """
    Returns dict with keys: prediction, confidence, ai_probability,
    top_indicators, reasoning, raw_response, error
    """
    truncated = truncate_to_words(text)
    full_prompt = SYSTEM_INSTRUCTION + "\n\n" + CLASSIFICATION_PROMPT.format(text=truncated)

    raw = ""
    for attempt in range(1, RETRY_LIMIT + 1):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    temperature=0.1,
                    max_output_tokens=512,
                )
            )

            if response.text is None:
                raise ValueError("response.text is None — likely a safety block or empty response")

            raw = response.text.strip()

            # Strip markdown fences if present
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
                raw = raw.strip()

            parsed = json.loads(raw)

            # Validate required keys
            required = {"prediction", "confidence", "ai_probability"}
            if not required.issubset(parsed.keys()):
                raise ValueError(f"Missing keys in response: {parsed.keys()}")

            parsed["raw_response"] = raw
            parsed["error"]        = None
            return parsed

        except Exception as e:
            print(f"\n    [attempt {attempt}/{RETRY_LIMIT}] ERROR: {e}")
            if raw:
                print(f"    RAW RESPONSE: {raw[:300]}")
            if attempt < RETRY_LIMIT:
                time.sleep(RETRY_DELAY * attempt)

    return {
        "prediction":     None,
        "confidence":     0.5,
        "ai_probability": 0.5,
        "top_indicators": [],
        "reasoning":      "All retries failed",
        "raw_response":   raw,
        "error":          "max retries exceeded"
    }


# ── Batch evaluation ──────────────────────────────────────────────────────────

def run_zero_shot_evaluation(
    texts:  list[str],
    labels: list[int],          # 0=human, 1=AI-generated
    api_key: str = API_KEY,
    requests_per_minute: int = 60,
    save_results_path: str = "zero_shot_results.csv"
) -> tuple[pd.DataFrame, dict]:
    """
    Classifies all papers zero-shot and computes full evaluation metrics.

    Parameters
    ----------
    texts   : raw paper texts
    labels  : ground-truth labels (0=human, 1=ai)
    api_key : Gemini API key
    requests_per_minute : rate limit (adjust for your tier)
    save_results_path   : path to save per-paper results CSV

    Returns
    -------
    results_df : DataFrame with per-paper predictions + metadata
    metrics    : dict of aggregate evaluation metrics
    """
    client = genai.Client(api_key=api_key)

    delay_between_requests = 60.0 / requests_per_minute

    records = []
    print(f"Zero-shot classification: {len(texts)} papers using {GEMINI_MODEL}")
    print(f"Rate limit: {requests_per_minute} req/min ({delay_between_requests:.1f}s delay)\n")

    for i, (text, label) in enumerate(zip(texts, labels)):
        print(f"[{i+1:03d}/{len(texts)}] ", end="", flush=True)

        result = classify_paper_zero_shot(text, client)

        # Convert prediction string to int label
        pred_label = None
        if result["prediction"] == "ai_generated":
            pred_label = 1
        elif result["prediction"] == "human":
            pred_label = 0
        # else: parse error — stays None, excluded from metrics

        record = {
            "index":          i,
            "true_label":     label,
            "pred_label":     pred_label,
            "ai_probability": result["ai_probability"],
            "confidence":     result["confidence"],
            "prediction_str": result["prediction"],
            "reasoning":      result["reasoning"],
            "top_indicators": " | ".join(result.get("top_indicators", [])),
            "parse_error":    result["error"] is not None,
            "error_msg":      result["error"],
        }
        records.append(record)

        status = "✓" if pred_label == label else ("✗" if pred_label is not None else "?")
        print(f"{status}  pred={result['prediction']}  conf={result['confidence']:.2f}  "
              f"true={'human' if label==0 else 'ai_generated'}")

        time.sleep(delay_between_requests)

    results_df = pd.DataFrame(records)
    results_df.to_csv(save_results_path, index=False)
    print(f"\nResults saved to: {save_results_path}")

    # ── Metrics (exclude failed parses) ───────────────────────────────────────
    valid     = results_df.dropna(subset=["pred_label"])
    n_errors  = results_df["parse_error"].sum()
    n_valid   = len(valid)

    if n_errors > 0:
        print(f"\n⚠ {n_errors}/{len(results_df)} papers had parse errors — excluded from metrics")

    true  = valid["true_label"].astype(int).values
    preds = valid["pred_label"].astype(int).values
    probs = valid["ai_probability"].values

    metrics = {
        "accuracy":        accuracy_score(true, preds),
        "precision_fake":  precision_score(true, preds, pos_label=1, zero_division=0),
        "recall_fake":     recall_score(true, preds, pos_label=1, zero_division=0),
        "f1_fake":         f1_score(true, preds, pos_label=1, zero_division=0),
        "roc_auc":         roc_auc_score(true, probs),
        "n_total":         len(results_df),
        "n_valid":         n_valid,
        "n_parse_errors":  n_errors,
        "parse_error_rate": n_errors / len(results_df)
    }

    print("\n=== Zero-shot LLM — Evaluation Results ===")
    print(classification_report(true, preds, target_names=["Human", "AI-Generated"]))
    print(f"ROC-AUC: {metrics['roc_auc']:.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(true, preds)}")
    print(f"\nParse error rate: {metrics['parse_error_rate']:.1%} ({n_errors}/{len(results_df)})")

    # ── Confidence calibration summary ────────────────────────────────────────
    print("\n=== Confidence Calibration ===")
    correct_mask = (preds == true)
    print(f"  Mean confidence (correct):   {valid.loc[valid.index[correct_mask], 'confidence'].mean():.3f}")
    print(f"  Mean confidence (incorrect): {valid.loc[valid.index[~correct_mask], 'confidence'].mean():.3f}")

    # ai_probability distribution by true class
    for cls, name in [(0, "Human"), (1, "AI-Generated")]:
        subset = valid[valid["true_label"] == cls]["ai_probability"]
        print(f"  ai_probability ({name}): mean={subset.mean():.3f}  std={subset.std():.3f}")

    return results_df, metrics


# ── Comparison helper ─────────────────────────────────────────────────────────

def compare_baselines(
    distilbert_cv_summary: dict,
    zero_shot_metrics: dict,
    ensemble_cv_summary: dict = None
):
    """
    Pretty-prints comparison table across all models.
    distilbert_cv_summary: output of run_distilbert_cv()[1]
    zero_shot_metrics:     output of run_zero_shot_evaluation()[1]
    ensemble_cv_summary:   dict with same structure (from your existing RF+GBM code)
    """
    rows = []

    if ensemble_cv_summary:
        rows.append({
            "Model": "Ensemble (RF+GBM)",
            "Accuracy":  f"{ensemble_cv_summary['accuracy']['mean']:.3f} ± {ensemble_cv_summary['accuracy']['std']:.3f}",
            "F1 (Fake)": f"{ensemble_cv_summary['f1']['mean']:.3f} ± {ensemble_cv_summary['f1']['std']:.3f}",
            "ROC-AUC":   f"{ensemble_cv_summary['roc_auc']['mean']:.3f} ± {ensemble_cv_summary['roc_auc']['std']:.3f}",
            "Note": "Interpretable, stable"
        })

    rows.append({
        "Model": "Fine-tuned DistilBERT",
        "Accuracy":  f"{distilbert_cv_summary['accuracy']['mean']:.3f} ± {distilbert_cv_summary['accuracy']['std']:.3f}",
        "F1 (Fake)": f"{distilbert_cv_summary['f1']['mean']:.3f} ± {distilbert_cv_summary['f1']['std']:.3f}",
        "ROC-AUC":   f"{distilbert_cv_summary['roc_auc']['mean']:.3f} ± {distilbert_cv_summary['roc_auc']['std']:.3f}",
        "Note": "Deep learning reference"
    })

    rows.append({
        "Model": "Zero-shot LLM (Gemini)",
        "Accuracy":  f"{zero_shot_metrics['accuracy']:.3f}",
        "F1 (Fake)": f"{zero_shot_metrics['f1_fake']:.3f}",
        "ROC-AUC":   f"{zero_shot_metrics['roc_auc']:.3f}",
        "Note": "No training required"
    })

    df = pd.DataFrame(rows).set_index("Model")
    print("\n=== Model Comparison ===")
    print(df.to_string())
    return df


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import os
    import json
    from sklearn.model_selection import train_test_split as sk_split

    api_key = os.environ.get("GEMINI_API_KEY", API_KEY)

    # ── Load data ─────────────────────────────────────────────────────────────
    df = pd.read_csv("data/final_dataset.csv")
    df["label_int"] = (df["label"] == "AI").astype(int)   # Human=0, AI=1

    texts  = df["text"].tolist()
    labels = df["label_int"].tolist()

    print(f"Dataset: {len(texts)} samples")
    print(f"Class distribution:\n{df['label'].value_counts()}")

    # ── Replicate identical 70/15/15 split from ensemble training ────────────
    X_temp, X_test, y_temp, y_test = sk_split(
        texts, labels, test_size=0.15, stratify=labels, random_state=42
    )
    X_train, X_val, y_train, y_val = sk_split(
        X_temp, y_temp, test_size=0.15 / 0.85, stratify=y_temp, random_state=42
    )
    print(f"Split — Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")

    # ── Run zero-shot on test set only (no training needed) ───────────────────
    # Zero-shot has no training phase; evaluate directly on held-out test set.
    os.makedirs("outputs/models", exist_ok=True)

    results_df, zs_metrics = run_zero_shot_evaluation(
        texts=X_test,
        labels=y_test,
        api_key=api_key,
        requests_per_minute=30,          # adjust to your Gemini API tier
        save_results_path="outputs/models/zero_shot_results.csv"
    )

    with open("outputs/models/zero_shot_metrics.json", "w") as f:
        json.dump(zs_metrics, f, indent=2)

    print("\n✓ Saved: outputs/models/zero_shot_results.csv, zero_shot_metrics.json")

    # ── Compare all models ────────────────────────────────────────────────────
    # Load DistilBERT CV summary (produced by distilbert_baseline.py)
    distilbert_cv_path = "outputs/models/distilbert_cv_summary.json"
    # Load ensemble CV summary (produced by ensemble training script)
    ensemble_cv_path   = "outputs/models/results.json"

    if os.path.exists(distilbert_cv_path) and os.path.exists(ensemble_cv_path):
        with open(distilbert_cv_path) as f:
            distilbert_cv_summary = json.load(f)
        with open(ensemble_cv_path) as f:
            ensemble_results = json.load(f)

        # Reformat ensemble CV to match {metric: {mean, std}} structure
        ensemble_cv_summary = ensemble_results["cv"]

        comparison_df = compare_baselines(
            distilbert_cv_summary=distilbert_cv_summary,
            zero_shot_metrics=zs_metrics,
            ensemble_cv_summary=ensemble_cv_summary
        )
        comparison_df.to_csv("outputs/models/model_comparison.csv")
        print("✓ Saved: outputs/models/model_comparison.csv")
    else:
        print("\n⚠ Run distilbert_baseline.py first to generate distilbert_cv_summary.json")
        print("  Skipping full comparison table.")